#!/bin/bash
# Sending write-file
# Usage: bacawf device-instance file-instance local-name [octet count] [pad value]
# If you want write to File 1 to Device 123 with local-name temp.txt,use the following command:
# bacawf 123 1 temp.txt


device_instance=123
file_instance=2
local_name=temp.txt

if [ -z "$1" ]; then
 local_name=temp.txt
else
 local_name=$1
fi

../writefile/bacawf $device_instance $file_instance $local_name
