#!/bin/bash
# Sending write-property request
# Usage: bacwp device-instance object-type object-instance property priority index tag value [tag value...]
# value can be optional input argument
# For further information see bacenum.h in include folder
# Example: write value of 100 to analog-output 1 of device 123 at priority 16
# bacwp 123 1 0 85 16 -1 4 100

device_instance=123
object_type=1
object_instance=0
property=85
priority=16
index=-1
tag=4
value=${1:-100}

../writeprop/bacwp $device_instance $object_type $object_instance $property $priority $index $tag $value

