#!/bin/bash
# Sending write-file
# Usage: bacawf device-instance file-instance local-name [octet count] [pad value]
# If you want write to File 1 to Device 123 with local-name temp.txt,use the following command:
# bacawf 123 1 temp.txt


device_instance=123
file_instance=1

if [ -z "$1" ]; then
 local_name=temp.txt
else
 local_name=$1
fi

if [ -z "$2" ]; then
 n=1
else
 n=$2
fi

# send request n times
counter=1
while [ $counter -le $n ]
do 
    ../writefile/bacawf $device_instance $file_instance $local_name $value
    sleep .01    
    ((counter++))
done

# move and rename by timestamp
filename=`date +%Y-%m-%d-%H-%M`
dir="awfsec"
filename+="-$dir"
local_name=${local_name:6}
filename+="-$local_name"
mv awf.dat measurements/$dir/$filename

