#!/bin/bash
# Sending read-file
# Usage: bacarf device-instance file-instance local-name
# If you want read File 1 from Device 123 and save it to temp.txt,use the following command:
# bacarf 123 1 temp.txt

device_instance=123
file_instance=1
local_name=temp.txt

if [ -z "$1" ]; then
 local_name=temp.txt
else
 local_name=$1
fi

if [ -z "$2" ]; then
 n=1
else
 n=$2
fi

# send request n times
counter=1
while [ $counter -le $n ]
do 
    ../readfile/bacarf $device_instance $file_instance $local_name
    sleep .01    
    ((counter++))
done

# move and rename by timestamp
filename=`date +%Y-%m-%d-%H-%M`
dir="arfsec"
filename+="-$dir"
local_name=${local_name:6}
filename+="-$local_name"
mv arf.dat measurements/$dir/$filename

