#!/bin/bash
# Sending read-file
# Usage: bacarf device-instance file-instance local-name
# If you want read File 1 from Device 123 and save it to temp.txt,use the following command:
# bacarf 123 1 temp.txt

device_instance=123
file_instance=1
local_name=temp.txt

if [ -z "$1" ]; then
 local_name=temp.txt
else
 local_name=$1
fi
../readfile/bacarf $device_instance $file_instance $local_name
