#!/bin/bash
# Sending read-property request
# Usage: bacrp device-instance object-type object-instance property [index]
# For further information see bacenum.h in include folder
# Example: read present-value from analog-output 1 on device 123
# bacrp 123 1 0 85 

#remove old measurement
rm test.txt

# initialize request parameters
device_instance=123
object_type=1
object_instance=0
property=85

# send request n times
counter=1
while [ $counter -le 10000 ]
do 
    ../readprop/bacrp $device_instance $object_type $object_instance $property
    sleep .01    
    ((counter++))
done

# move and rename by timestamp
d=`date +%Y-%m-%d-%H-%M`
mv test.txt measurements/$d


